[package]
name = "ic_websocket_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.72"
candid = "0.8.4"
ic-agent = "0.24.1"
ic-cdk = "0.9.2"
ic-cdk-macros = "0.7.0"
serde = "1.0.176"
serde_cbor = "0.11.2"
tokio = { version = "1.29.1", features = ["full"] }
ring = "0.16.20"
serde_bytes = "0.11.12"
tokio-tungstenite = "0.20.0"
ed25519-compact = "2.0.4"
futures-util = "0.3.28"
structopt = "0.3.21"
tracing = "0.1"
tracing-subscriber = "0.2"

[dev-dependencies]
websocket = "0.26.5"