[package]
name = "ic_websocket_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.72"
candid = "0.9.0"
ic-agent = { workspace = true }
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = "1.0.176"
serde_cbor = "0.11.2"
tokio = { version = "1.29.1", features = ["full"] }
tokio-native-tls = "0.3.1"
native-tls = "0.2.11"
tokio-util = "0.7.8"
serde_bytes = "0.11.12"
tokio-tungstenite = "0.20.0"
futures-util = "0.3.28"
structopt = "0.3.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "std", "json", "env-filter"] }
tracing-appender = "0.2"
ic-identity = { version = "0.1.0", path = "../ic-identity" }
rand = "0.8"

[dev-dependencies]
websocket = "0.26.5"