[workspace]
members = [
    "src/ic-websocket-gateway",
    "src/ic-identity",
    "src/scripts",
    "src/concurrent-map",
    "tests/src/test_canister_rs",
]
default-members = ["src/ic-websocket-gateway"]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.70.0"
repository = "https://github.com/omnia-network/ic-websocket-gateway"
description = "IC Websocket Gateway workspace"
license = "MIT"

[workspace.dependencies]
candid = "0.9.3"
ic-agent = "0.30.2"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = "1.0.176"
reqwest = "0.11.7"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.40"

