[workspace]
members = [
    "src/ic-websocket-gateway",
    "src/ic-identity",
    "src/scripts",
    "tests/test_canister_rs/src/test_canister_rs",
]
default-members = [
    "src/ic-websocket-gateway",
]

[workspace.package]
edition = "2021"
rust-version = "1.70.0"
repository = "https://github.com/omnia-network/ic-websocket-gateway"
description = "IC Websocket Gateway workspace"
license = "MIT"

[workspace.dependencies]
candid = "0.9.3"
ic-agent = { git = "https://github.com/omnia-network/agent-rs", rev = "8c23cfe313aea75ab53cd71353c476002513ad3c" }
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = "1.0.176"
reqwest = "0.11.7"
