[workspace]
members = [
    "src/ic-websocket-gateway",
    "src/ic-identity",
    "src/scripts",
    "tests/test_canister_rs/src/test_canister_rs",
]
default-members = [
    "src/ic-websocket-gateway",
]

[workspace.dependencies]
candid = "0.9.3"
ic-agent = { git = "https://github.com/omnia-network/agent-rs", rev = "7bbf9b65bf7700b030e8f83447f397321fb02dcd" }
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = "1.0.176"
