services:
  ic_websocket_gateway:
    image: omniadevs/ic-websocket-gateway:latest
    container_name: ic-websocket-gateway
    restart: unless-stopped
    ports:
      - ${LISTEN_PORT}:443
    command:
      [
        "--gateway-address",
        "0.0.0.0:443",
        "--ic-network-url",
        "${IC_URL}",
        "--polling-interval",
        "${POLLING_INTERVAL}",
        "--min-incoming-interval",
        "${MIN_INCOMING_INTERVAL}",
        "--tls-certificate-pem-path",
        "/ic-ws-gateway/data/certs/live/${DOMAIN_NAME}/fullchain.pem",
        "--tls-certificate-key-pem-path",
        "/ic-ws-gateway/data/certs/live/${DOMAIN_NAME}/privkey.pem",
        "--telemetry-jaeger-agent-endpoint",
        "${TELEMETRY_JAEGER_AGENT_ENDPOINT}",
      ]
    environment:
      - RUST_LOG_FILE=${RUST_LOG_FILE}
      - RUST_LOG_STDOUT=${RUST_LOG_STDOUT}
      - RUST_LOG_TELEMETRY=${RUST_LOG_TELEMETRY}
    volumes:
      - ./volumes/ic-ws-gateway/data:/ic-ws-gateway/data
    networks:
      - ic-ws-gateway-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    profiles:
      - jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    networks:
      - ic-ws-gateway-network

networks:
  ic-ws-gateway-network:
    name: ic-ws-gateway-network
