services:
    ic_websocket_gateway:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ic-websocket-gateway
        container_name: ic-websocket-gateway
        restart: unless-stopped
        ports:
            - ${LISTEN_PORT}:443
        command:
            [
                "--gateway-address",
                "0.0.0.0:443",
                "--subnet-url",
                "${IC_URL}",
                "--polling-interval",
                "${POLLING_INTERVAL}",
                "--tls-certificate-pem-path",
                "/ic-ws-gateway/data/certs/live/${DOMAIN_NAME}/fullchain.pem",
                "--tls-certificate-key-pem-path",
                "/ic-ws-gateway/data/certs/live/${DOMAIN_NAME}/privkey.pem",
            ]
        environment:
            - RUST_LOG=${RUST_LOG}
        volumes:
            - ./volumes/ic-ws-gateway/data:/ic-ws-gateway/data
        networks:
            - ic-ws-gateway-network

networks:
    ic-ws-gateway-network:
        name: ic-ws-gateway-network
