receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp:
    endpoint: ${GRAFANA_TEMPO_ENDPOINT}
    headers:
      authorization: Basic ${GRAFANA_TEMPO_ACCESS_TOKEN}
    tls:
      insecure: ${GRAFANA_TEMPO_LOCAL}
#  prometheus:
#      endpoint: "0.0.0.0:9090"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
#    metrics:
#        receivers: [ otlp ]
#        exporters: [ prometheus ]
