global:
  scrape_interval: 10s
scrape_configs:
#  - job_name: 'otlp'
#    static_configs:
#      - targets: [ '0.0.0.0:9090' ]
  - job_name: gateway
    honor_labels: true
    static_configs:
      - targets: [ 'ic_websocket_gateway:9000' ]
