name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cp .env.example .env
    - name: publish
      run: docker compose -f docker-compose.yml -f docker-compose-prod.yml up
