name: IC WS Gateway tests

# only run when a commit is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "tests/package-lock.json"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
      - uses: aviate-labs/setup-dfx@v0.2.6
        with:
          dfx-version: 0.15.1
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Run unit tests
        run: ./scripts/ci_cd_test_unit.sh
      - name: Install integration tests dependencies
        run: ./scripts/install_integration_test_deps.sh
      - name: Run integration tests
        run: ./scripts/ci_cd_test_integration.sh
