name: IC WS Gateway tests

# only run when a commit is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "tests/integration/package-lock.json"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
      - uses: aviate-labs/setup-dfx@v0.2.6
        with:
          dfx-version: 0.15.0
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          workspaces: |
            .
            tests/test_canister_rs
      - name: Install tests dependencies
        run: ./scripts/install_test_dependencies.sh
      - name: Run unit tests
        run: ./scripts/ci_cd_test_unit.sh
      - name: Run integration tests
        run: ./scripts/ci_cd_test_integration.sh
